#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#   TRUTH MD Host Platform — Full VPS Setup Script
#   Run from inside the extracted project folder as root.
#
#   Usage (interactive):
#     bash vps-deploy/setup.sh
#
#   Usage (non-interactive — pass all args):
#     bash vps-deploy/setup.sh <domain> <port> <database_url> \
#       <jwt_secret> <admin_username> <admin_password> \
#       <resend_api_key> <app_url> \
#       [payflow_api_key] [payflow_api_secret] [payflow_account_id] \
#       [github_token]
# ═══════════════════════════════════════════════════════════════════

set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
ok()   { echo -e "${GREEN}[OK]${NC}    $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Detect project root (where this script lives) ─────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      TRUTH MD Host Platform — VPS Installer      ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Project directory: ${CYAN}${PROJECT_DIR}${NC}"
echo ""

# ── Root check ────────────────────────────────────────────────────
[ "$EUID" -ne 0 ] && fail "Please run as root: sudo bash vps-deploy/setup.sh"

# ── Collect config ────────────────────────────────────────────────
if [ -n "$1" ]; then
    DOMAIN="$1"
    APP_PORT="${2:-5000}"
    DATABASE_URL="$3"
    JWT_SECRET="$4"
    ADMIN_USERNAME="$5"
    ADMIN_PASSWORD="$6"
    RESEND_API_KEY="$7"
    APP_URL="${8:-https://$1}"
    PAYFLOW_API_KEY="${9:-}"
    PAYFLOW_API_SECRET="${10:-}"
    PAYFLOW_ACCOUNT_ID="${11:-}"
    GITHUB_TOKEN="${12:-}"
else
    echo -e "${YELLOW}Interactive setup — press Enter to accept defaults.${NC}"
    echo ""

    read -rp "  Domain (e.g. hosts.courtneytech.xyz): " DOMAIN
    read -rp "  App port [5000]: " APP_PORT;             APP_PORT="${APP_PORT:-5000}"
    read -rp "  Neon DATABASE_URL (postgres://...): "    DATABASE_URL
    read -rp "  JWT secret (any random string): "        JWT_SECRET
    read -rp "  Admin username: "                         ADMIN_USERNAME
    read -rsp " Admin password: "                         ADMIN_PASSWORD; echo ""
    read -rp "  Resend API key (re_...): "                RESEND_API_KEY
    read -rp "  App URL [https://$DOMAIN]: "              APP_URL; APP_URL="${APP_URL:-https://$DOMAIN}"
    echo ""
    echo -e "${YELLOW}  Optional — press Enter to skip:${NC}"
    read -rp "  Payflow API key:     " PAYFLOW_API_KEY
    read -rp "  Payflow API secret:  " PAYFLOW_API_SECRET
    read -rp "  Payflow account ID:  " PAYFLOW_ACCOUNT_ID
    read -rp "  GitHub token (private bot repos): " GITHUB_TOKEN
fi

INSTALL_DIR="$PROJECT_DIR"

echo ""
log "Domain:      $DOMAIN"
log "Port:        $APP_PORT"
log "App URL:     $APP_URL"
log "Install dir: $INSTALL_DIR"
echo ""

# ── System update ─────────────────────────────────────────────────
log "Updating system packages..."
apt-get update -y -qq
ok "System updated."

# ── Install Git ───────────────────────────────────────────────────
command -v git &>/dev/null || apt-get install -y git
ok "Git: $(git --version)"

# ── Install Node.js 20 ────────────────────────────────────────────
NODE_VERSION="20"
if ! command -v node &>/dev/null || \
   [[ "$(node -e 'process.stdout.write(process.version.split(".")[0].replace("v",""))')" -lt "$NODE_VERSION" ]]; then
    log "Installing Node.js ${NODE_VERSION}..."
    apt-get install -y curl ca-certificates
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
    apt-get install -y nodejs
fi
ok "Node.js: $(node -v)  |  npm: $(npm -v)"

# ── Install PM2 ───────────────────────────────────────────────────
command -v pm2 &>/dev/null || npm install -g pm2 --quiet
ok "PM2: $(pm2 -v)"

# ── Install Nginx ─────────────────────────────────────────────────
command -v nginx &>/dev/null || apt-get install -y nginx
ok "Nginx: $(nginx -v 2>&1)"

# ── Install Certbot ───────────────────────────────────────────────
command -v certbot &>/dev/null || apt-get install -y certbot python3-certbot-nginx
ok "Certbot installed."

# ── Create bots directory ─────────────────────────────────────────
mkdir -p "$INSTALL_DIR/bots"
ok "Bots directory ready."

# ── Write .env ────────────────────────────────────────────────────
log "Writing .env..."
cat > "$INSTALL_DIR/.env" <<EOF
# TRUTH MD Host Platform — generated by setup.sh

DATABASE_URL=${DATABASE_URL}

JWT_SECRET=${JWT_SECRET}

ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

PORT=${APP_PORT}
NODE_ENV=production

APP_URL=${APP_URL}

RESEND_API_KEY=${RESEND_API_KEY}

GITHUB_TOKEN=${GITHUB_TOKEN}

PAYFLOW_API_KEY=${PAYFLOW_API_KEY}
PAYFLOW_API_SECRET=${PAYFLOW_API_SECRET}
PAYFLOW_ACCOUNT_ID=${PAYFLOW_ACCOUNT_ID}
EOF
ok ".env written."

# ── Install npm dependencies ──────────────────────────────────────
log "Installing npm dependencies..."
cd "$INSTALL_DIR"
npm install --production --silent
ok "Dependencies installed."

# ── Write PM2 ecosystem file ──────────────────────────────────────
log "Writing PM2 config..."
cat > "$INSTALL_DIR/ecosystem.config.js" <<EOF
module.exports = {
  apps: [{
    name:               'truth-host-platform',
    script:             'index.js',
    cwd:                '${INSTALL_DIR}',
    instances:          1,
    autorestart:        true,
    watch:              false,
    max_memory_restart: '512M',
    env_file:           '${INSTALL_DIR}/.env',
    env: {
      NODE_ENV: 'production',
      PORT:     ${APP_PORT}
    }
  }]
};
EOF
ok "PM2 config written."

# ── Configure Nginx ───────────────────────────────────────────────
log "Configuring Nginx for $DOMAIN → localhost:$APP_PORT..."
NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"
cat > "$NGINX_CONF" <<EOF
server {
    listen 80;
    server_name ${DOMAIN};

    client_max_body_size 50M;

    location / {
        proxy_pass         http://localhost:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 120s;
    }
}
EOF

rm -f /etc/nginx/sites-enabled/default
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/
nginx -t && systemctl reload nginx
ok "Nginx configured."

# ── SSL Certificate ───────────────────────────────────────────────
log "Requesting SSL certificate..."
if certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
    -m "admin@courtneytech.xyz" --redirect 2>&1; then
    ok "SSL certificate installed."
else
    warn "SSL skipped — point your DNS A record to this server's IP first, then run:"
    warn "  certbot --nginx -d $DOMAIN"
fi

# ── SSL auto-renewal via cron ─────────────────────────────────────
(crontab -l 2>/dev/null | grep -v certbot; \
 echo "0 3 * * * certbot renew --quiet && systemctl reload nginx") | crontab -
ok "SSL auto-renewal scheduled."

# ── Start with PM2 ───────────────────────────────────────────────
log "Starting app with PM2..."
cd "$INSTALL_DIR"
pm2 delete truth-host-platform 2>/dev/null || true
pm2 start ecosystem.config.js
pm2 save

log "Enabling PM2 on reboot..."
PM2_STARTUP=$(pm2 startup systemd -u root --hp /root 2>&1 | grep "sudo env" | tail -1)
[ -n "$PM2_STARTUP" ] && eval "$PM2_STARTUP" || true
pm2 save
ok "PM2 startup enabled."

# ── Done ─────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Installation complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  URL:         ${CYAN}${APP_URL}${NC}"
echo -e "  Admin login: ${CYAN}${ADMIN_USERNAME}${NC}"
echo ""
echo -e "  Useful commands:"
echo -e "  ${YELLOW}pm2 status${NC}"
echo -e "  ${YELLOW}pm2 logs truth-host-platform${NC}"
echo -e "  ${YELLOW}pm2 restart truth-host-platform${NC}"
echo ""
pm2 status
